packages:
  - core
  - plugins/cors
  - plugins/graphql
  - plugins/static

catalog:
  '@types/node': ^24.13.3
  oxlint: ^1.78.0
  oxfmt: ^0.63.0
  publint: ^0.3.23
  tsdown: ^0.22.14
  typescript: ^7.0.2

injectWorkspacePackages: true
linkWorkspacePackages: true
includeWorkspaceRoot: true
